spring.application.name=Ai_Trading_Coach_backend


spring.datasource.url=jdbc:mysql://localhost:3306/ai_trading
spring.datasource.username=root
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

alphavantage.api.key = 5LVSKXA11U4HPU68
app.market.symbols = RELIANCE.BSE,HDFCBANK.BSE,INFY.BSE,TCS.BSE,ICICIBANK.BSE,SBIN.BSE,BHARTIARTL.BSE,ITC.BSE,HINDUNILVR.BSE,LT.BSE,BAJFINANCE.BSE,AXISBANK.BSE,WIPRO.BSE,KOTAKBANK.BSE,TATAMOTORS.BSE

# Cache Expiration (Time-To-Live)
spring.cache.redis.time-to-live=2h